# -*- coding: utf-8 -*-
"""SampleComplexityExperiments.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hry8zjoIVn6qi84ejHTx8-jrLtODVPAN
"""

import sample_complexity
from matplotlib import pyplot as plt

print("Computing sample complexity!")

m_perceptron = sample_complexity.sample_complexity(sample_complexity.perceptron,100)

sample_complexity.plot_complexity(0.5,2,100,'linear','Perceptron',m_perceptron)

m_least_squares = sample_complexity.sample_complexity(sample_complexity.least_squares,100)

sample_complexity.plot_complexity(0.3,1,100,'linear','Least Squares',m_least_squares)

m_winnow = sample_complexity.sample_complexity(sample_complexity.winnow,300)

sample_complexity.plot_complexity(3,5.5,300,'log','winnow',m_winnow)

m_one_nn  = sample_complexity.sample_complexity(sample_complexity.one_nn,13)

sample_complexity.plot_complexity(0.1,0.2,13,'exp','one nn',m_one_nn)